_target_: torchrecipes.vision.core.datamodule.torchvision_data_module.TorchVisionDataModule
datasets: ???
batch_size: 32
drop_last: false
normalize: false
num_workers: 16
pin_memory: false
seed: 42
val_split: null
