accuracy_top1:
  _target_: torchrecipes.vision.image_classification.metrics.multilabel_accuracy.MultilabelAccuracy
  top_k: 1
accuracy_top5:
  _target_: torchrecipes.vision.image_classification.metrics.multilabel_accuracy.MultilabelAccuracy
  top_k: 5
