_target_: torchrecipes.text.doc_classification.datamodule.doc_classification.DocClassificationDataModule.from_config
columns:
- text
- label
label_column: label
batch_size: 16
num_workers: 0
drop_last: False
pin_memory: False
