defaults:
  - module/optim: adamw
  - module/model: xlmrbase_classifier_tiny
  - datamodule: doc_classification_datamodule
  - datamodule/dataset: sst2_dataset
  - trainer: cpu
  - transform: doc_classification_transform_tiny
  - _self_
