defaults:
  - module/optim: adamw
  - module/model: xlmrbase_classifier
  - datamodule: doc_classification_datamodule
  - datamodule/dataset: sst2_dataset
  - trainer: cpu
  - transform: doc_classification_transform
  - _self_

transform:
  num_labels: 2
