_target_: pytorch_lightning.trainer.Trainer
default_root_dir: null
accelerator: gpu
devices: null
strategy: ddp
max_epochs: 20
fast_dev_run: false
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: /tmp/logs
callbacks:
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: /tmp/checkpoints
- _target_: pytorch_lightning.callbacks.LearningRateMonitor
