_target_: torchrecipes.vision.image_classification.train_app.ImageClassificationTrainApp

defaults:
  - _self_
  # module
  - schema/module: image_classification_module_conf
  - module/model: resnet18
  - module/loss: cross_entropy
  - module/optim: sgd_partial
  - module/metrics: accuracy
  # datamodule
  - datamodule: torchvision_datamodule
  - datamodule/datasets: cifar10
  # trainer
  - schema/trainer: trainer
  - trainer: cpu
  # callbacks
  - callbacks: default

trainer:
  # benchmark flag is likely to increase the training speed if input sizes don’t
  # change. However, if it does, then it will likely make training slower.
  # NOTE: turn off this flag if training is expected to be deterministic.
  benchmark: true

hydra:
  searchpath:
    - pkg://torchrecipes.core.conf
