_target_: pytorch_lightning.trainer.Trainer
accelerator: cpu
devices: null
strategy: null
max_epochs: 1
default_root_dir: ""
enable_checkpointing: true
fast_dev_run: false
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: /tmp/logs
