# use _partial_ to instantiate an optimizer callable, which returns
# an optimizer in configure_optimizer.
_target_: torch.optim.SGD
_partial_: true
lr: 0.1
weight_decay: 1e-4
momentum: 0.9
nesterov: False
