# Black + usort
[[linter]]
code = 'UFMT'
include_patterns = [
    '**/*.py',
]
command = [
    'python3',
    'tools/linter/ufmt_linter.py',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python3',
    'tools/linter/pip_init.py',
    '--dry-run={{DRYRUN}}',
    'black==24.2.0',
    'ufmt==2.5.1',
    'usort==1.0.8',
]
is_formatter = true
